git-hooks: permit own push also with others Acked-by:
The pre-push script verifies that every commit by the person pushing has
at least one Reviewed-by tag by someone other than the author.
Add an additional check permitting push without Reviewed-by as long as
there is an Acked-by.

Signed-off-by: Leif Lindholm <leif.lindholm@linaro.org>

diff --git a/git-hooks/pre-push b/git-hooks/pre-push
--- a/git-hooks/pre-push
+++ b/git-hooks/pre-push
@@ -47,8 +47,11 @@ check_reviewed()
 
     reviewed=`git rev-list -n 1 --grep "^Reviewed-by: $REVIEWER\$" "$1^..$1"`
     if [ -z "$reviewed" ]; then
-        echo "$1 missing 'Reviewed-by:'!" >&2
-	return 1
+        reviewed=`git rev-list -n 1 --grep "^Acked-by: $REVIEWER\$" "$1^..$1"`
+        if [ -z "$reviewed" ]; then
+            echo "$1 missing 'Reviewed-by:'!" >&2
+	    return 1
+        fi
     fi
 }
 
